[recent]
title = "뉴스타파 ─ 뉴스"
url = "http://newstapa.org/recent"
entrySelector = "article.article"
titleSelector = "h6.font-weight-bold"
linkSelector = "h6.font-weight-bold a"
contentSelector = "h6.font-weight-bold a"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[project]
title = "뉴스타파 ─ 프로젝트"
url = "http://newstapa.org/projects/list"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article a"
contentSelector = "p.float-right.mt-2 span"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"

[data]
title = "뉴스타파 ─ 데이터"
url = "http://newstapa.org/projects/data"
entrySelector = "div.list_section-slider-row-block div div.col-lg-3.col-md-6.columns"
titleSelector = "h6.font-weight-bold"
linkSelector = "article.article a"
contentSelector = "p.float-right.mt-2 span"
dateSelector = "p.float-right.mt-2.date"
dateFormat = "yyyy.MM.dd"
imageSelector = "figure.article-image img.d-block.w-100"
waitUntil = "networkidle"
